version: '3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=YOURMYSQLROOTPASSWORDHERE
    env_file:
      - db.env

  app:
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - VIRTUAL_HOST=dg1sekcloud.spdns.eu
      - LETSENCRYPT_HOST=dg1sekcloud.spdns.eu
      - LETSENCRYPT_EMAIL=siegfried.loeffler@gmx.net
      - MYSQL_HOST=db
    env_file:
      - db.env
    depends_on:
      - db
    networks:
      - proxy-tier
      - default

  web:
    build: ./web
    restart: always
    volumes:
       - /var/www/html:/usr/share/nginx/html:ro
       - /var/nginx/conf:/etc/nginx:ro
       - /etc/letsencrypt:/etc/letsencrypt:ro 
    environment:
      - VIRTUAL_HOST=dg1sek.spdns.eu
      - LETSENCRYPT_HOST=dg1sek.spdns.eu
      - LETSENCRYPT_EMAIL=siegfried.loeffler@gmx.net
    depends_on:
      - app
    networks:
      - proxy-tier
      - default

#  wordpress:
#  image: wordpress
#    links:
#      - db:mysql
#    environment:
#      - MYSQL_ROOT_PASSWORD=YOURMYSQLROOTPASSWORDHERE
#      - WORDPRESS_DB_PASSWORD=YOURWORDPRESSPASSWORDHERE
#    ports:
#      - 8080:80
#    volumes:
#      - ./code:/code
#      - ./html:/var/www/html

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - ENABLE_IPv6=true
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

volumes:
  db:
  nextcloud:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:
